### ISSUE TITLE
Programs that import this take about 1s to start

### ISSUE THREAD

**Issue by talwrii** [0k/kids.cache#9]
Verified on Python 2 (but probably also a problem on Python 3)

# Proof!

```
time python -c 'import sys'; time python -c 'import kids.cache'
python -c 'import sys'  0.08s user 0.01s system 97% cpu 0.086 total
python -c 'import kids.cache'  0.90s user 0.09s system 96% cpu 1.025 total
```

# Unconfirmed speculation

I think this is related to slow python entry points (see
[fastentrypoints](https://github.com/ninjaaron/fast-entry_points).

**Comment by vaab** [comment]
The "only" thing getting imported that could induce such important lags is ``pkg_resource``, and this is used only to ensure namespacing of ``kids``. It seems that there is a [more mature solution](https://docs.python.org/3/library/pkgutil.html) around that I'm currently investigating.

It also seem to depend how ``kids.cache`` was installed on the system. For instance, I don't get hardly any real difference on my dev install (symlinks and custom lib in ``PYTHONPATH``), but I could reproduce a sensible difference (around 150ms) by installing it on a clean ubuntu docker and using the ``pip install kids.cache`` command.

I'll keep you informed.
Thank you for the report.

**Comment by vaab** [comment]
I confirm that replacing the current lines in ``src/kids/__init__.py`` by:

```
from pkgutil import extend_path
__path__ = extend_path(__path__, __name__)
```

... is passing the current ...

```
time python -c 'import kids.cache'
```
... from ~200ms to ~20ms on my docker install.

I still need to make sure everything is alright with this namespacing and all packaging solution on various python versions, and I don't have any time left today. So I'll try to push the patch tomorrow.

Meanwhile, it would be nice if you could check that this fixes your issue on your installation. I'll push anyway this modification if it doesn't break anything as it seems it is now the recommended way to do namespacing and is improving dramatically the import time at least on one platform.

**Comment by talwrii** [comment]
Yep, that seems to fix the problem for me:

```
cat /home/tom/.local/lib/python2.7/site-packages/kids/__init__.py ; time python -c 'import sys'; time python -c 'import kids.cache'
# See http://peak.telecommunity.com/DevCenter/setuptools#namespace-packages
from pkgutil import extend_path
__path__ = extend_path(__path__, __name__)
python -c 'import sys'  0.04s user 0.01s system 99% cpu 0.049 total
python -c 'import kids.cache'  0.05s user 0.00s system 98% cpu 0.053 total
```

I get the impression that `pkg_resource` load time is in some way proportional to the number of packages you have installed.

**Comment by vaab** [comment]
Committed with release on PyPI as ``0.0.7``...
